apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: nslocal
  name: accountservice
  labels:
    app: accountservice
spec:
  template:
    metadata:
      labels:
        app: accountservice
        tier: web
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - name: accountservice
        image: registry.gitlab.com/resourceallocationsystem/accountservice:@KVERSION
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: nslocal
  name: accountservice
  labels:
    app: accountservice
spec:
  type: NodePort
  selector:
    app: accountservice
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
